export const names = {
  "bulbasaur": "Bulbasaur",
  "ivysaur": "Ivysaur",
  "venusaur": "Venusaur",
  "charmander": "Charmander",
  "charmeleon": "Charmeleon",
  "charizard": "Charizard",
  "squirtle": "Squirtle",
  "wartortle": "Wartortle",
  "blastoise": "Blastoise",
  "caterpie": "Caterpie",
  "metapod": "Metapod",
  "butterfree": "Butterfree",
  "weedle": "Weedle",
  "kakuna": "Kakuna",
  "beedrill": "Beedrill",
  "pidgey": "Pidgey",
  "pidgeotto": "Pidgeotto",
  "pidgeot": "Pidgeot",
  "rattata": "Rattata",
  "raticate": "Raticate",
  "spearow": "Spearow",
  "fearow": "Fearow",
  "ekans": "Ekans",
  "arbok": "Arbok",
  "pikachu": "Pikachu",
  "raichu": "Raichu",
  "sandshrew": "Sandshrew",
  "sandslash": "Sandslash",
  "nidoran-f": "Nidoran♀",
  "nidorina": "Nidorina",
  "nidoqueen": "Nidoqueen",
  "nidoran-m": "Nidoran♂",
  "nidorino": "Nidorino",
  "nidoking": "Nidoking",
  "clefairy": "Clefairy",
  "clefable": "Clefable",
  "vulpix": "Vulpix",
  "ninetales": "Ninetales",
  "jigglypuff": "Jigglypuff",
  "wigglytuff": "Wigglytuff",
  "zubat": "Zubat",
  "golbat": "Golbat",
  "oddish": "Oddish",
  "gloom": "Gloom",
  "vileplume": "Vileplume",
  "paras": "Paras",
  "parasect": "Parasect",
  "venonat": "Venonat",
  "venomoth": "Venomoth",
  "diglett": "Diglett",
  "dugtrio": "Dugtrio",
  "meowth": "Meowth",
  "persian": "Persian",
  "psyduck": "Psyduck",
  "golduck": "Golduck",
  "mankey": "Mankey",
  "primeape": "Primeape",
  "growlithe": "Growlithe",
  "arcanine": "Arcanine",
  "poliwag": "Poliwag",
  "poliwhirl": "Poliwhirl",
  "poliwrath": "Poliwrath",
  "abra": "Abra",
  "kadabra": "Kadabra",
  "alakazam": "Alakazam",
  "machop": "Machop",
  "machoke": "Machoke",
  "machamp": "Machamp",
  "bellsprout": "Bellsprout",
  "weepinbell": "Weepinbell",
  "victreebel": "Victreebel",
  "tentacool": "Tentacool",
  "tentacruel": "Tentacruel",
  "geodude": "Geodude",
  "graveler": "Graveler",
  "golem": "Golem",
  "ponyta": "Ponyta",
  "rapidash": "Rapidash",
  "slowpoke": "Slowpoke",
  "slowbro": "Slowbro",
  "magnemite": "Magnemite",
  "magneton": "Magneton",
  "farfetchd": "Farfetch'd",
  "doduo": "Doduo",
  "dodrio": "Dodrio",
  "seel": "Seel",
  "dewgong": "Dewgong",
  "grimer": "Grimer",
  "muk": "Muk",
  "shellder": "Shellder",
  "cloyster": "Cloyster",
  "gastly": "Gastly",
  "haunter": "Haunter",
  "gengar": "Gengar",
  "onix": "Onix",
  "drowzee": "Drowzee",
  "hypno": "Hypno",
  "krabby": "Krabby",
  "kingler": "Kingler",
  "voltorb": "Voltorb",
  "electrode": "Electrode",
  "exeggcute": "Exeggcute",
  "exeggutor": "Exeggutor",
  "cubone": "Cubone",
  "marowak": "Marowak",
  "hitmonlee": "Hitmonlee",
  "hitmonchan": "Hitmonchan",
  "lickitung": "Lickitung",
  "koffing": "Koffing",
  "weezing": "Weezing",
  "rhyhorn": "Rhyhorn",
  "rhydon": "Rhydon",
  "chansey": "Chansey",
  "tangela": "Tangela",
  "kangaskhan": "Kangaskhan",
  "horsea": "Horsea",
  "seadra": "Seadra",
  "goldeen": "Goldeen",
  "seaking": "Seaking",
  "staryu": "Staryu",
  "starmie": "Starmie",
  "mr-mime": "Mr. Mime",
  "scyther": "Scyther",
  "jynx": "Jynx",
  "electabuzz": "Electabuzz",
  "magmar": "Magmar",
  "pinsir": "Pinsir",
  "tauros": "Tauros",
  "magikarp": "Magikarp",
  "gyarados": "Gyarados",
  "lapras": "Lapras",
  "ditto": "Ditto",
  "eevee": "Eevee",
  "vaporeon": "Vaporeon",
  "jolteon": "Jolteon",
  "flareon": "Flareon",
  "porygon": "Porygon",
  "omanyte": "Omanyte",
  "omastar": "Omastar",
  "kabuto": "Kabuto",
  "kabutops": "Kabutops",
  "aerodactyl": "Aerodactyl",
  "snorlax": "Snorlax",
  "articuno": "Articuno",
  "zapdos": "Zapdos",
  "moltres": "Moltres",
  "dratini": "Dratini",
  "dragonair": "Dragonair",
  "dragonite": "Dragonite",
  "mewtwo": "Mewtwo",
  "mew": "Mew",
  "chikorita": "Chikorita",
  "bayleef": "Bayleef",
  "meganium": "Meganium",
  "cyndaquil": "Cyndaquil",
  "quilava": "Quilava",
  "typhlosion": "Typhlosion",
  "totodile": "Totodile",
  "croconaw": "Croconaw",
  "feraligatr": "Feraligatr",
  "sentret": "Sentret",
  "furret": "Furret",
  "hoothoot": "Hoothoot",
  "noctowl": "Noctowl",
  "ledyba": "Ledyba",
  "ledian": "Ledian",
  "spinarak": "Spinarak",
  "ariados": "Ariados",
  "crobat": "Crobat",
  "chinchou": "Chinchou",
  "lanturn": "Lanturn",
  "pichu": "Pichu",
  "cleffa": "Cleffa",
  "igglybuff": "Igglybuff",
  "togepi": "Togepi",
  "togetic": "Togetic",
  "natu": "Natu",
  "xatu": "Xatu",
  "mareep": "Mareep",
  "flaaffy": "Flaaffy",
  "ampharos": "Ampharos",
  "bellossom": "Bellossom",
  "marill": "Marill",
  "azumarill": "Azumarill",
  "sudowoodo": "Sudowoodo",
  "politoed": "Politoed",
  "hoppip": "Hoppip",
  "skiploom": "Skiploom",
  "jumpluff": "Jumpluff",
  "aipom": "Aipom",
  "sunkern": "Sunkern",
  "sunflora": "Sunflora",
  "yanma": "Yanma",
  "wooper": "Wooper",
  "quagsire": "Quagsire",
  "espeon": "Espeon",
  "umbreon": "Umbreon",
  "murkrow": "Murkrow",
  "slowking": "Slowking",
  "misdreavus": "Misdreavus",
  "unown": "Unown",
  "wobbuffet": "Wobbuffet",
  "girafarig": "Girafarig",
  "pineco": "Pineco",
  "forretress": "Forretress",
  "dunsparce": "Dunsparce",
  "gligar": "Gligar",
  "steelix": "Steelix",
  "snubbull": "Snubbull",
  "granbull": "Granbull",
  "qwilfish": "Qwilfish",
  "scizor": "Scizor",
  "shuckle": "Shuckle",
  "heracross": "Heracross",
  "sneasel": "Sneasel",
  "teddiursa": "Teddiursa",
  "ursaring": "Ursaring",
  "slugma": "Slugma",
  "magcargo": "Magcargo",
  "swinub": "Swinub",
  "piloswine": "Piloswine",
  "corsola": "Corsola",
  "remoraid": "Remoraid",
  "octillery": "Octillery",
  "delibird": "Delibird",
  "mantine": "Mantine",
  "skarmory": "Skarmory",
  "houndour": "Houndour",
  "houndoom": "Houndoom",
  "kingdra": "Kingdra",
  "phanpy": "Phanpy",
  "donphan": "Donphan",
  "porygon2": "Porygon2",
  "stantler": "Stantler",
  "smeargle": "Smeargle",
  "tyrogue": "Tyrogue",
  "hitmontop": "Hitmontop",
  "smoochum": "Smoochum",
  "elekid": "Elekid",
  "magby": "Magby",
  "miltank": "Miltank",
  "blissey": "Blissey",
  "raikou": "Raikou",
  "entei": "Entei",
  "suicune": "Suicune",
  "larvitar": "Larvitar",
  "pupitar": "Pupitar",
  "tyranitar": "Tyranitar",
  "lugia": "Lugia",
  "ho-oh": "Ho-Oh",
  "celebi": "Celebi",
  "treecko": "Treecko",
  "grovyle": "Grovyle",
  "sceptile": "Sceptile",
  "torchic": "Torchic",
  "combusken": "Combusken",
  "blaziken": "Blaziken",
  "mudkip": "Mudkip",
  "marshtomp": "Marshtomp",
  "swampert": "Swampert",
  "poochyena": "Poochyena",
  "mightyena": "Mightyena",
  "zigzagoon": "Zigzagoon",
  "linoone": "Linoone",
  "wurmple": "Wurmple",
  "silcoon": "Silcoon",
  "beautifly": "Beautifly",
  "cascoon": "Cascoon",
  "dustox": "Dustox",
  "lotad": "Lotad",
  "lombre": "Lombre",
  "ludicolo": "Ludicolo",
  "seedot": "Seedot",
  "nuzleaf": "Nuzleaf",
  "shiftry": "Shiftry",
  "taillow": "Taillow",
  "swellow": "Swellow",
  "wingull": "Wingull",
  "pelipper": "Pelipper",
  "ralts": "Ralts",
  "kirlia": "Kirlia",
  "gardevoir": "Gardevoir",
  "surskit": "Surskit",
  "masquerain": "Masquerain",
  "shroomish": "Shroomish",
  "breloom": "Breloom",
  "slakoth": "Slakoth",
  "vigoroth": "Vigoroth",
  "slaking": "Slaking",
  "nincada": "Nincada",
  "ninjask": "Ninjask",
  "shedinja": "Shedinja",
  "whismur": "Whismur",
  "loudred": "Loudred",
  "exploud": "Exploud",
  "makuhita": "Makuhita",
  "hariyama": "Hariyama",
  "azurill": "Azurill",
  "nosepass": "Nosepass",
  "skitty": "Skitty",
  "delcatty": "Delcatty",
  "sableye": "Sableye",
  "mawile": "Mawile",
  "aron": "Aron",
  "lairon": "Lairon",
  "aggron": "Aggron",
  "meditite": "Meditite",
  "medicham": "Medicham",
  "electrike": "Electrike",
  "manectric": "Manectric",
  "plusle": "Plusle",
  "minun": "Minun",
  "volbeat": "Volbeat",
  "illumise": "Illumise",
  "roselia": "Roselia",
  "gulpin": "Gulpin",
  "swalot": "Swalot",
  "carvanha": "Carvanha",
  "sharpedo": "Sharpedo",
  "wailmer": "Wailmer",
  "wailord": "Wailord",
  "numel": "Numel",
  "camerupt": "Camerupt",
  "torkoal": "Torkoal",
  "spoink": "Spoink",
  "grumpig": "Grumpig",
  "spinda": "Spinda",
  "trapinch": "Trapinch",
  "vibrava": "Vibrava",
  "flygon": "Flygon",
  "cacnea": "Cacnea",
  "cacturne": "Cacturne",
  "swablu": "Swablu",
  "altaria": "Altaria",
  "zangoose": "Zangoose",
  "seviper": "Seviper",
  "lunatone": "Lunatone",
  "solrock": "Solrock",
  "barboach": "Barboach",
  "whiscash": "Whiscash",
  "corphish": "Corphish",
  "crawdaunt": "Crawdaunt",
  "baltoy": "Baltoy",
  "claydol": "Claydol",
  "lileep": "Lileep",
  "cradily": "Cradily",
  "anorith": "Anorith",
  "armaldo": "Armaldo",
  "feebas": "Feebas",
  "milotic": "Milotic",
  "castform": "Castform",
  "kecleon": "Kecleon",
  "shuppet": "Shuppet",
  "banette": "Banette",
  "duskull": "Duskull",
  "dusclops": "Dusclops",
  "tropius": "Tropius",
  "chimecho": "Chimecho",
  "absol": "Absol",
  "wynaut": "Wynaut",
  "snorunt": "Snorunt",
  "glalie": "Glalie",
  "spheal": "Spheal",
  "sealeo": "Sealeo",
  "walrein": "Walrein",
  "clamperl": "Clamperl",
  "huntail": "Huntail",
  "gorebyss": "Gorebyss",
  "relicanth": "Relicanth",
  "luvdisc": "Luvdisc",
  "bagon": "Bagon",
  "shelgon": "Shelgon",
  "salamence": "Salamence",
  "beldum": "Beldum",
  "metang": "Metang",
  "metagross": "Metagross",
  "regirock": "Regirock",
  "regice": "Regice",
  "registeel": "Registeel",
  "latias": "Latias",
  "latios": "Latios",
  "kyogre": "Kyogre",
  "groudon": "Groudon",
  "rayquaza": "Rayquaza",
  "jirachi": "Jirachi",
  "deoxys-normal": "Deoxys",
  "turtwig": "Turtwig",
  "grotle": "Grotle",
  "torterra": "Torterra",
  "chimchar": "Chimchar",
  "monferno": "Monferno",
  "infernape": "Infernape",
  "piplup": "Piplup",
  "prinplup": "Prinplup",
  "empoleon": "Empoleon",
  "starly": "Starly",
  "staravia": "Staravia",
  "staraptor": "Staraptor",
  "bidoof": "Bidoof",
  "bibarel": "Bibarel",
  "kricketot": "Kricketot",
  "kricketune": "Kricketune",
  "shinx": "Shinx",
  "luxio": "Luxio",
  "luxray": "Luxray",
  "budew": "Budew",
  "roserade": "Roserade",
  "cranidos": "Cranidos",
  "rampardos": "Rampardos",
  "shieldon": "Shieldon",
  "bastiodon": "Bastiodon",
  "burmy": "Burmy",
  "wormadam-plant": "Wormadam",
  "mothim": "Mothim",
  "combee": "Combee",
  "vespiquen": "Vespiquen",
  "pachirisu": "Pachirisu",
  "buizel": "Buizel",
  "floatzel": "Floatzel",
  "cherubi": "Cherubi",
  "cherrim": "Cherrim",
  "shellos": "Shellos",
  "gastrodon": "Gastrodon",
  "ambipom": "Ambipom",
  "drifloon": "Drifloon",
  "drifblim": "Drifblim",
  "buneary": "Buneary",
  "lopunny": "Lopunny",
  "mismagius": "Mismagius",
  "honchkrow": "Honchkrow",
  "glameow": "Glameow",
  "purugly": "Purugly",
  "chingling": "Chingling",
  "stunky": "Stunky",
  "skuntank": "Skuntank",
  "bronzor": "Bronzor",
  "bronzong": "Bronzong",
  "bonsly": "Bonsly",
  "mime-jr": "Mime Jr.",
  "happiny": "Happiny",
  "chatot": "Chatot",
  "spiritomb": "Spiritomb",
  "gible": "Gible",
  "gabite": "Gabite",
  "garchomp": "Garchomp",
  "munchlax": "Munchlax",
  "riolu": "Riolu",
  "lucario": "Lucario",
  "hippopotas": "Hippopotas",
  "hippowdon": "Hippowdon",
  "skorupi": "Skorupi",
  "drapion": "Drapion",
  "croagunk": "Croagunk",
  "toxicroak": "Toxicroak",
  "carnivine": "Carnivine",
  "finneon": "Finneon",
  "lumineon": "Lumineon",
  "mantyke": "Mantyke",
  "snover": "Snover",
  "abomasnow": "Abomasnow",
  "weavile": "Weavile",
  "magnezone": "Magnezone",
  "lickilicky": "Lickilicky",
  "rhyperior": "Rhyperior",
  "tangrowth": "Tangrowth",
  "electivire": "Electivire",
  "magmortar": "Magmortar",
  "togekiss": "Togekiss",
  "yanmega": "Yanmega",
  "leafeon": "Leafeon",
  "glaceon": "Glaceon",
  "gliscor": "Gliscor",
  "mamoswine": "Mamoswine",
  "porygon-z": "Porygon-Z",
  "gallade": "Gallade",
  "probopass": "Probopass",
  "dusknoir": "Dusknoir",
  "froslass": "Froslass",
  "rotom": "Rotom",
  "uxie": "Uxie",
  "mesprit": "Mesprit",
  "azelf": "Azelf",
  "dialga": "Dialga",
  "palkia": "Palkia",
  "heatran": "Heatran",
  "regigigas": "Regigigas",
  "giratina-altered": "Giratina",
  "cresselia": "Cresselia",
  "phione": "Phione",
  "manaphy": "Manaphy",
  "darkrai": "Darkrai",
  "shaymin-land": "Shaymin",
  "arceus": "Arceus",
  "victini": "Victini",
  "snivy": "Snivy",
  "servine": "Servine",
  "serperior": "Serperior",
  "tepig": "Tepig",
  "pignite": "Pignite",
  "emboar": "Emboar",
  "oshawott": "Oshawott",
  "dewott": "Dewott",
  "samurott": "Samurott",
  "patrat": "Patrat",
  "watchog": "Watchog",
  "lillipup": "Lillipup",
  "herdier": "Herdier",
  "stoutland": "Stoutland",
  "purrloin": "Purrloin",
  "liepard": "Liepard",
  "pansage": "Pansage",
  "simisage": "Simisage",
  "pansear": "Pansear",
  "simisear": "Simisear",
  "panpour": "Panpour",
  "simipour": "Simipour",
  "munna": "Munna",
  "musharna": "Musharna",
  "pidove": "Pidove",
  "tranquill": "Tranquill",
  "unfezant": "Unfezant",
  "blitzle": "Blitzle",
  "zebstrika": "Zebstrika",
  "roggenrola": "Roggenrola",
  "boldore": "Boldore",
  "gigalith": "Gigalith",
  "woobat": "Woobat",
  "swoobat": "Swoobat",
  "drilbur": "Drilbur",
  "excadrill": "Excadrill",
  "audino": "Audino",
  "timburr": "Timburr",
  "gurdurr": "Gurdurr",
  "conkeldurr": "Conkeldurr",
  "tympole": "Tympole",
  "palpitoad": "Palpitoad",
  "seismitoad": "Seismitoad",
  "throh": "Throh",
  "sawk": "Sawk",
  "sewaddle": "Sewaddle",
  "swadloon": "Swadloon",
  "leavanny": "Leavanny",
  "venipede": "Venipede",
  "whirlipede": "Whirlipede",
  "scolipede": "Scolipede",
  "cottonee": "Cottonee",
  "whimsicott": "Whimsicott",
  "petilil": "Petilil",
  "lilligant": "Lilligant",
  "basculin-red-striped": "Basculin",
  "sandile": "Sandile",
  "krokorok": "Krokorok",
  "krookodile": "Krookodile",
  "darumaka": "Darumaka",
  "darmanitan-standard": "Darmanitan",
  "maractus": "Maractus",
  "dwebble": "Dwebble",
  "crustle": "Crustle",
  "scraggy": "Scraggy",
  "scrafty": "Scrafty",
  "sigilyph": "Sigilyph",
  "yamask": "Yamask",
  "cofagrigus": "Cofagrigus",
  "tirtouga": "Tirtouga",
  "carracosta": "Carracosta",
  "archen": "Archen",
  "archeops": "Archeops",
  "trubbish": "Trubbish",
  "garbodor": "Garbodor",
  "zorua": "Zorua",
  "zoroark": "Zoroark",
  "minccino": "Minccino",
  "cinccino": "Cinccino",
  "gothita": "Gothita",
  "gothorita": "Gothorita",
  "gothitelle": "Gothitelle",
  "solosis": "Solosis",
  "duosion": "Duosion",
  "reuniclus": "Reuniclus",
  "ducklett": "Ducklett",
  "swanna": "Swanna",
  "vanillite": "Vanillite",
  "vanillish": "Vanillish",
  "vanilluxe": "Vanilluxe",
  "deerling": "Deerling",
  "sawsbuck": "Sawsbuck",
  "emolga": "Emolga",
  "karrablast": "Karrablast",
  "escavalier": "Escavalier",
  "foongus": "Foongus",
  "amoonguss": "Amoonguss",
  "frillish": "Frillish",
  "jellicent": "Jellicent",
  "alomomola": "Alomomola",
  "joltik": "Joltik",
  "galvantula": "Galvantula",
  "ferroseed": "Ferroseed",
  "ferrothorn": "Ferrothorn",
  "klink": "Klink",
  "klang": "Klang",
  "klinklang": "Klinklang",
  "tynamo": "Tynamo",
  "eelektrik": "Eelektrik",
  "eelektross": "Eelektross",
  "elgyem": "Elgyem",
  "beheeyem": "Beheeyem",
  "litwick": "Litwick",
  "lampent": "Lampent",
  "chandelure": "Chandelure",
  "axew": "Axew",
  "fraxure": "Fraxure",
  "haxorus": "Haxorus",
  "cubchoo": "Cubchoo",
  "beartic": "Beartic",
  "cryogonal": "Cryogonal",
  "shelmet": "Shelmet",
  "accelgor": "Accelgor",
  "stunfisk": "Stunfisk",
  "mienfoo": "Mienfoo",
  "mienshao": "Mienshao",
  "druddigon": "Druddigon",
  "golett": "Golett",
  "golurk": "Golurk",
  "pawniard": "Pawniard",
  "bisharp": "Bisharp",
  "bouffalant": "Bouffalant",
  "rufflet": "Rufflet",
  "braviary": "Braviary",
  "vullaby": "Vullaby",
  "mandibuzz": "Mandibuzz",
  "heatmor": "Heatmor",
  "durant": "Durant",
  "deino": "Deino",
  "zweilous": "Zweilous",
  "hydreigon": "Hydreigon",
  "larvesta": "Larvesta",
  "volcarona": "Volcarona",
  "cobalion": "Cobalion",
  "terrakion": "Terrakion",
  "virizion": "Virizion",
  "tornadus-incarnate": "Tornadus",
  "thundurus-incarnate": "Thundurus",
  "reshiram": "Reshiram",
  "zekrom": "Zekrom",
  "landorus-incarnate": "Landorus",
  "kyurem": "Kyurem",
  "keldeo-ordinary": "Keldeo",
  "meloetta-aria": "Meloetta",
  "genesect": "Genesect",
  "chespin": "Chespin",
  "quilladin": "Quilladin",
  "chesnaught": "Chesnaught",
  "fennekin": "Fennekin",
  "braixen": "Braixen",
  "delphox": "Delphox",
  "froakie": "Froakie",
  "frogadier": "Frogadier",
  "greninja": "Greninja",
  "bunnelby": "Bunnelby",
  "diggersby": "Diggersby",
  "fletchling": "Fletchling",
  "fletchinder": "Fletchinder",
  "talonflame": "Talonflame",
  "scatterbug": "Scatterbug",
  "spewpa": "Spewpa",
  "vivillon": "Vivillon",
  "litleo": "Litleo",
  "pyroar": "Pyroar",
  "flabebe": "Flabébé",
  "floette": "Floette",
  "florges": "Florges",
  "skiddo": "Skiddo",
  "gogoat": "Gogoat",
  "pancham": "Pancham",
  "pangoro": "Pangoro",
  "furfrou": "Furfrou",
  "espurr": "Espurr",
  "meowstic-male": "Meowstic",
  "honedge": "Honedge",
  "doublade": "Doublade",
  "aegislash-shield": "Aegislash",
  "spritzee": "Spritzee",
  "aromatisse": "Aromatisse",
  "swirlix": "Swirlix",
  "slurpuff": "Slurpuff",
  "inkay": "Inkay",
  "malamar": "Malamar",
  "binacle": "Binacle",
  "barbaracle": "Barbaracle",
  "skrelp": "Skrelp",
  "dragalge": "Dragalge",
  "clauncher": "Clauncher",
  "clawitzer": "Clawitzer",
  "helioptile": "Helioptile",
  "heliolisk": "Heliolisk",
  "tyrunt": "Tyrunt",
  "tyrantrum": "Tyrantrum",
  "amaura": "Amaura",
  "aurorus": "Aurorus",
  "sylveon": "Sylveon",
  "hawlucha": "Hawlucha",
  "dedenne": "Dedenne",
  "carbink": "Carbink",
  "goomy": "Goomy",
  "sliggoo": "Sliggoo",
  "goodra": "Goodra",
  "klefki": "Klefki",
  "phantump": "Phantump",
  "trevenant": "Trevenant",
  "pumpkaboo-average": "Pumpkaboo",
  "gourgeist-average": "Gourgeist",
  "bergmite": "Bergmite",
  "avalugg": "Avalugg",
  "noibat": "Noibat",
  "noivern": "Noivern",
  "xerneas": "Xerneas",
  "yveltal": "Yveltal",
  "zygarde-50": "Zygarde",
  "diancie": "Diancie",
  "hoopa": "Hoopa Confined",
  "volcanion": "Volcanion",
  "rowlet": "Rowlet",
  "dartrix": "Dartrix",
  "decidueye": "Decidueye",
  "litten": "Litten",
  "torracat": "Torracat",
  "incineroar": "Incineroar",
  "popplio": "Popplio",
  "brionne": "Brionne",
  "primarina": "Primarina",
  "pikipek": "Pikipek",
  "trumbeak": "Trumbeak",
  "toucannon": "Toucannon",
  "yungoos": "Yungoos",
  "gumshoos": "Gumshoos",
  "grubbin": "Grubbin",
  "charjabug": "Charjabug",
  "vikavolt": "Vikavolt",
  "crabrawler": "Crabrawler",
  "crabominable": "Crabominable",
  "oricorio-baile": "Oricorio",
  "cutiefly": "Cutiefly",
  "ribombee": "Ribombee",
  "rockruff": "Rockruff",
  "lycanroc-midday": "Lycanroc",
  "wishiwashi-solo": "Wishiwashi",
  "mareanie": "Mareanie",
  "toxapex": "Toxapex",
  "mudbray": "Mudbray",
  "mudsdale": "Mudsdale",
  "dewpider": "Dewpider",
  "araquanid": "Araquanid",
  "fomantis": "Fomantis",
  "lurantis": "Lurantis",
  "morelull": "Morelull",
  "shiinotic": "Shiinotic",
  "salandit": "Salandit",
  "salazzle": "Salazzle",
  "stufful": "Stufful",
  "bewear": "Bewear",
  "bounsweet": "Bounsweet",
  "steenee": "Steenee",
  "tsareena": "Tsareena",
  "comfey": "Comfey",
  "oranguru": "Oranguru",
  "passimian": "Passimian",
  "wimpod": "Wimpod",
  "golisopod": "Golisopod",
  "sandygast": "Sandygast",
  "palossand": "Palossand",
  "pyukumuku": "Pyukumuku",
  "type-null": "Type: Null",
  "silvally": "Silvally",
  "minior-red-meteor": "Minior",
  "komala": "Komala",
  "turtonator": "Turtonator",
  "togedemaru": "Togedemaru",
  "mimikyu-disguised": "Mimikyu",
  "bruxish": "Bruxish",
  "drampa": "Drampa",
  "dhelmise": "Dhelmise",
  "jangmo-o": "Jangmo-o",
  "hakamo-o": "Hakamo-o",
  "kommo-o": "Kommo-o",
  "tapu-koko": "Tapu Koko",
  "tapu-lele": "Tapu Lele",
  "tapu-bulu": "Tapu Bulu",
  "tapu-fini": "Tapu Fini",
  "cosmog": "Cosmog",
  "cosmoem": "Cosmoem",
  "solgaleo": "Solgaleo",
  "lunala": "Lunala",
  "nihilego": "Nihilego",
  "buzzwole": "Buzzwole",
  "pheromosa": "Pheromosa",
  "xurkitree": "Xurkitree",
  "celesteela": "Celesteela",
  "kartana": "Kartana",
  "guzzlord": "Guzzlord",
  "necrozma": "Necrozma",
  "magearna": "Magearna",
  "marshadow": "Marshadow",
  "poipole": "Poipole",
  "naganadel": "Naganadel",
  "stakataka": "Stakataka",
  "blacephalon": "Blacephalon",
  "zeraora": "Zeraora",
  "meltan": "Meltan",
  "melmetal": "Melmetal",
  "grookey": "Grookey",
  "thwackey": "Thwackey",
  "rillaboom": "Rillaboom",
  "scorbunny": "Scorbunny",
  "raboot": "Raboot",
  "cinderace": "Cinderace",
  "sobble": "Sobble",
  "drizzile": "Drizzile",
  "inteleon": "Inteleon",
  "skwovet": "Skwovet",
  "greedent": "Greedent",
  "rookidee": "Rookidee",
  "corvisquire": "Corvisquire",
  "corviknight": "Corviknight",
  "blipbug": "Blipbug",
  "dottler": "Dottler",
  "orbeetle": "Orbeetle",
  "nickit": "Nickit",
  "thievul": "Thievul",
  "gossifleur": "Gossifleur",
  "eldegoss": "Eldegoss",
  "wooloo": "Wooloo",
  "dubwool": "Dubwool",
  "chewtle": "Chewtle",
  "drednaw": "Drednaw",
  "yamper": "Yamper",
  "boltund": "Boltund",
  "rolycoly": "Rolycoly",
  "carkol": "Carkol",
  "coalossal": "Coalossal",
  "applin": "Applin",
  "flapple": "Flapple",
  "appletun": "Appletun",
  "silicobra": "Silicobra",
  "sandaconda": "Sandaconda",
  "cramorant": "Cramorant",
  "arrokuda": "Arrokuda",
  "barraskewda": "Barraskewda",
  "toxel": "Toxel",
  "toxtricity-amped": "Toxtricity",
  "sizzlipede": "Sizzlipede",
  "centiskorch": "Centiskorch",
  "clobbopus": "Clobbopus",
  "grapploct": "Grapploct",
  "sinistea": "Sinistea",
  "polteageist": "Polteageist",
  "hatenna": "Hatenna",
  "hattrem": "Hattrem",
  "hatterene": "Hatterene",
  "impidimp": "Impidimp",
  "morgrem": "Morgrem",
  "grimmsnarl": "Grimmsnarl",
  "obstagoon": "Obstagoon",
  "perrserker": "Perrserker",
  "cursola": "Cursola",
  "sirfetchd": "Sirfetch’d",
  "mr-rime": "Mr. Rime",
  "runerigus": "Runerigus",
  "milcery": "Milcery",
  "alcremie": "Alcremie",
  "falinks": "Falinks",
  "pincurchin": "Pincurchin",
  "snom": "Snom",
  "frosmoth": "Frosmoth",
  "stonjourner": "Stonjourner",
  "eiscue-ice": "Eiscue",
  "indeedee-male": "Indeedee",
  "morpeko-full-belly": "Morpeko",
  "cufant": "Cufant",
  "copperajah": "Copperajah",
  "dracozolt": "Dracozolt",
  "arctozolt": "Arctozolt",
  "dracovish": "Dracovish",
  "arctovish": "Arctovish",
  "duraludon": "Duraludon",
  "dreepy": "Dreepy",
  "drakloak": "Drakloak",
  "dragapult": "Dragapult",
  "zacian": "Zacian",
  "zamazenta": "Zamazenta",
  "eternatus": "Eternatus",
  "kubfu": "Kubfu",
  "urshifu-single-strike": "Single Strike Urshifu",
  "zarude": "Zarude",
  "regieleki": "Regieleki",
  "regidrago": "Regidrago",
  "glastrier": "Glastrier",
  "spectrier": "Spectrier",
  "calyrex": "Calyrex",
  "wyrdeer": "Wyrdeer",
  "kleavor": "Kleavor",
  "ursaluna": "Ursaluna",
  "basculegion-male": "Basculegion",
  "sneasler": "Sneasler",
  "overqwil": "Overqwil",
  "enamorus-incarnate": "Enamorus",
  "sprigatito": "Sprigatito",
  "floragato": "Floragato",
  "meowscarada": "Meowscarada",
  "fuecoco": "Fuecoco",
  "crocalor": "Crocalor",
  "skeledirge": "Skeledirge",
  "quaxly": "Quaxly",
  "quaxwell": "Quaxwell",
  "quaquaval": "Quaquaval",
  "lechonk": "Lechonk",
  "oinkologne": "Oinkologne",
  "tarountula": "Tarountula",
  "spidops": "Spidops",
  "nymble": "Nymble",
  "lokix": "Lokix",
  "pawmi": "Pawmi",
  "pawmo": "Pawmo",
  "pawmot": "Pawmot",
  "tandemaus": "Tandemaus",
  "maushold": "Maushold",
  "fidough": "Fidough",
  "dachsbun": "Dachsbun",
  "smoliv": "Smoliv",
  "dolliv": "Dolliv",
  "arboliva": "Arboliva",
  "squawkabilly": "Squawkabilly",
  "nacli": "Nacli",
  "naclstack": "Naclstack",
  "garganacl": "Garganacl",
  "charcadet": "Charcadet",
  "armarouge": "Armarouge",
  "ceruledge": "Ceruledge",
  "tadbulb": "Tadbulb",
  "bellibolt": "Bellibolt",
  "wattrel": "Wattrel",
  "kilowattrel": "Kilowattrel",
  "maschiff": "Maschiff",
  "mabosstiff": "Mabosstiff",
  "shroodle": "Shroodle",
  "grafaiai": "Grafaiai",
  "bramblin": "Bramblin",
  "brambleghast": "Brambleghast",
  "toedscool": "Toedscool",
  "toedscruel": "Toedscruel",
  "capsakid": "Capsakid",
  "scovillain": "Scovillain",
  "rellor": "Rellor",
  "rabsca": "Rabsca",
  "flittle": "Flittle",
  "espathra": "Espathra",
  "tinkatink": "Tinkatink",
  "tinkatuff": "Tinkatuff",
  "tinkaton": "Tinkaton",
  "wiglett": "Wiglett",
  "wugtrio": "Wugtrio",
  "bombirdier": "Bombirdier",
  "finizen": "Finizen",
  "palafin": "Palafin",
  "varoom": "Varoom",
  "revavroom": "Revavroom",
  "cyclizar": "Cyclizar",
  "orthworm": "Orthworm",
  "glimmet": "Glimmet",
  "glimmora": "Glimmora",
  "greavard": "Greavard",
  "houndstone": "Houndstone",
  "flamigo": "Flamigo",
  "cetoddle": "Cetoddle",
  "cetitan": "Cetitan",
  "veluza": "Veluza",
  "dondozo": "Dondozo",
  "tatsugiri": "Tatsugiri",
  "annihilape": "Annihilape",
  "clodsire": "Clodsire",
  "farigiraf": "Farigiraf",
  "dudunsparce": "Dudunsparce",
  "kingambit": "Kingambit",
  "great-tusk": "Great Tusk",
  "scream-tail": "Scream Tail",
  "brute-bonnet": "Brute Bonnet",
  "flutter-mane": "Flutter Mane",
  "slither-wing": "Slither Wing",
  "sandy-shocks": "Sandy Shocks",
  "iron-treads": "Iron Treads",
  "iron-bundle": "Iron Bundle",
  "iron-hands": "Iron Hands",
  "iron-jugulis": "Iron Jugulis",
  "iron-moth": "Iron Moth",
  "iron-thorns": "Iron Thorns",
  "frigibax": "Frigibax",
  "arctibax": "Arctibax",
  "baxcalibur": "Baxcalibur",
  "gimmighoul": "Gimmighoul",
  "gholdengo": "Gholdengo",
  "wo-chien": "Wo-Chien",
  "chien-pao": "Chien-Pao",
  "ting-lu": "Ting-Lu",
  "chi-yu": "Chi-Yu",
  "roaring-moon": "Roaring Moon",
  "iron-valiant": "Iron Valiant",
  "koraidon": "Koraidon",
  "miraidon": "Miraidon",
  "walking-wake": "Walking Wake",
  "iron-leaves": "Iron Leaves",
  "dipplin": "Dipplin",
  "poltchageist": "Poltchageist",
  "sinistcha" : "Sinistcha",
  "okidogi": "Okidogi",
  "munkidori": "Munkidori",
  "fezandipiti": "Fezandipiti",
  "ogerpon": "Ogerpon",
  "archaludon": "Archaludon",
  "hydrapple": "Hydrapple",
  "gouging-fire": "Gouging Fire",
  "raging-bolt": "Raging Bolt",
  "iron-boulder": "Iron Boulder",
  "iron-crown": "Iron Crown",
  "terapagos": "Terapagos",
  "pecharunt": "Pecharunt",
  "deoxys-attack": "Deoxys",
  "deoxys-defense": "Deoxys",
  "deoxys-speed": "Deoxys",
  "wormadam-sandy": "Wormadam",
  "wormadam-trash": "Wormadam",
  "shaymin-sky": "Shaymin",
  "giratina-origin": "Giratina",
  "rotom-heat": "Rotom",
  "rotom-wash": "Rotom",
  "rotom-frost": "Rotom",
  "rotom-fan": "Rotom",
  "rotom-mow": "Rotom",
  "castform-sunny": "Castform",
  "castform-rainy": "Castform",
  "castform-snowy": "Castform",
  "basculin-blue-striped": "Basculin",
  "darmanitan-zen": "Darmanitan",
  "meloetta-pirouette": "Meloetta",
  "tornadus-therian": "Tornadus",
  "thundurus-therian": "Thundurus",
  "landorus-therian": "Landorus",
  "kyurem-black": "Kyurem",
  "kyurem-white": "Kyurem",
  "keldeo-resolute": "Keldeo",
  "meowstic-female": "Meowstic",
  "aegislash-blade": "Aegislash",
  "pumpkaboo-small": "Pumpkaboo",
  "pumpkaboo-large": "Pumpkaboo",
  "pumpkaboo-super": "Pumpkaboo",
  "gourgeist-small": "Gourgeist",
  "gourgeist-large": "Gourgeist",
  "gourgeist-super": "Gourgeist",
  "venusaur-mega": "Mega Venusaur",
  "charizard-mega-x": "Mega Charizard X",
  "charizard-mega-y": "Mega Charizard Y",
  "blastoise-mega": "Mega Blastoise",
  "alakazam-mega": "Mega Alakazam",
  "gengar-mega": "Mega Gengar",
  "kangaskhan-mega": "Mega Kangaskhan",
  "pinsir-mega": "Mega Pinsir",
  "gyarados-mega": "Mega Gyarados",
  "aerodactyl-mega": "Mega Aerodactyl",
  "mewtwo-mega-x": "Mega Mewtwo X",
  "mewtwo-mega-y": "Mega Mewtwo Y",
  "ampharos-mega": "Mega Ampharos",
  "scizor-mega": "Mega Scizor",
  "heracross-mega": "Mega Heracross",
  "houndoom-mega": "Mega Houndoom",
  "tyranitar-mega": "Mega Tyranitar",
  "blaziken-mega": "Mega Blaziken",
  "gardevoir-mega": "Mega Gardevoir",
  "mawile-mega": "Mega Mawile",
  "aggron-mega": "Mega Aggron",
  "medicham-mega": "Mega Medicham",
  "manectric-mega": "Mega Manectric",
  "banette-mega": "Mega Banette",
  "absol-mega": "Mega Absol",
  "garchomp-mega": "Mega Garchomp",
  "lucario-mega": "Mega Lucario",
  "abomasnow-mega": "Mega Abomasnow",
  "floette-eternal": "Eternal Flower Floette",
  "latias-mega": "Mega Latias",
  "latios-mega": "Mega Latios",
  "swampert-mega": "Mega Swampert",
  "sceptile-mega": "Mega Sceptile",
  "sableye-mega": "Mega Sableye",
  "altaria-mega": "Mega Altaria",
  "gallade-mega": "Mega Gallade",
  "audino-mega": "Mega Audino",
  "sharpedo-mega": "Mega Sharpedo",
  "slowbro-mega": "Mega Slowbro",
  "steelix-mega": "Mega Steelix",
  "pidgeot-mega": "Mega Pidgeot",
  "glalie-mega": "Mega Glalie",
  "diancie-mega": "Mega Diancie",
  "metagross-mega": "Mega Metagross",
  "kyogre-primal": "Primal Kyogre",
  "groudon-primal": "Primal Groudon",
  "rayquaza-mega": "Mega Rayquaza",
  "pikachu-rock-star": "Pikachu Rock Star",
  "pikachu-belle": "Pikachu Belle",
  "pikachu-pop-star": "Pikachu Pop Star",
  "pikachu-phd": "Pikachu, Ph.D.",
  "pikachu-libre": "Pikachu Libre",
  "pikachu-cosplay": "Cosplay Pikachu",
  "hoopa-unbound": "Hoopa Unbound",
  "camerupt-mega": "Mega Camerupt",
  "lopunny-mega": "Mega Lopunny",
  "salamence-mega": "Mega Salamence",
  "beedrill-mega": "Mega Beedrill",
  "rattata-alola": "Alolan Rattata",
  "raticate-alola": "Alolan Raticate",
  "raticate-totem-alola": "Totem Alolan Raticate",
  "pikachu-original-cap": "Original Cap Pikachu",
  "pikachu-hoenn-cap": "Hoenn Cap Pikachu",
  "pikachu-sinnoh-cap": "Sinnoh Cap Pikachu",
  "pikachu-unova-cap": "Unova Cap Pikachu",
  "pikachu-kalos-cap": "Kalos Cap Pikachu",
  "pikachu-alola-cap": "Alola Cap Pikachu",
  "raichu-alola": "Alolan Raichu",
  "sandshrew-alola": "Alolan Sandshrew",
  "sandslash-alola": "Alolan Sandslash",
  "vulpix-alola": "Alolan Vulpix",
  "ninetales-alola": "Alolan Ninetales",
  "diglett-alola": "Alolan Diglett",
  "dugtrio-alola": "Alolan Dugtrio",
  "meowth-alola": "Alolan Meowth",
  "persian-alola": "Alolan Persian",
  "geodude-alola": "Alolan Geodude",
  "graveler-alola": "Alolan Graveler",
  "golem-alola": "Alolan Golem",
  "grimer-alola": "Alolan Grimer",
  "muk-alola": "Alolan Muk",
  "exeggutor-alola": "Alolan Exeggutor",
  "marowak-alola": "Alolan Marowak",
  "greninja-battle-bond": "Ash-Greninja",
  "greninja-ash": "Ash-Greninja",
  "zygarde-10-power-construct": "Zygarde",
  "zygarde-50-power-construct": "Zygarde",
  "zygarde-complete": "Zygarde",
  "gumshoos-totem": "Totem Gumshoos",
  "vikavolt-totem": "Totem Vikavolt",
  "oricorio-pom-pom": "Pom-Pom Oricorio",
  "oricorio-pau": "Pa'u Oricorio",
  "oricorio-sensu": "Sensu Oricorio",
  "lycanroc-midnight": "Lycanroc",
  "wishiwashi-school": "Wishiwashi",
  "lurantis-totem": "Totem Lurantis",
  "salazzle-totem": "Totem Salazzle",
  "minior-orange-meteor": "Minior",
  "minior-yellow-meteor": "Minior",
  "minior-green-meteor": "Minior",
  "minior-blue-meteor": "Minior",
  "minior-indigo-meteor": "Minior",
  "minior-violet-meteor": "Minior",
  "minior-red": "Minior",
  "minior-orange": "Minior",
  "minior-yellow": "Minior",
  "minior-green": "Minior",
  "minior-blue": "Minior",
  "minior-indigo": "Minior",
  "minior-violet": "Minior",
  "mimikyu-busted": "Mimikyu",
  "mimikyu-totem-disguised": "Totem Mimikyu",
  "mimikyu-totem-busted": "Totem Mimikyu",
  "kommo-o-totem": "Totem Kommo-o",
  "magearna-original": "Magearna",
  "pikachu-partner-cap": "Partner Cap Pikachu",
  "marowak-totem": "Totem Marowak",
  "ribombee-totem": "Totem Ribombee",
  "rockruff-own-tempo": "Rockruff",
  "lycanroc-dusk": "Lycanroc",
  "araquanid-totem": "Totem Araquanid",
  "togedemaru-totem": "Totem Togedemaru",
  "necrozma-dusk": "Dusk Mane Necrozma",
  "necrozma-dawn": "Dawn Wings Necrozma",
  "necrozma-ultra": "Ultra Necrozma",
  "pikachu-starter": "Pikachu",
  "eevee-starter": "Eevee",
  "pikachu-world-cap": "World Cap Pikachu",
  "meowth-galar": "Galarian Meowth",
  "ponyta-galar": "Galarian Ponyta",
  "rapidash-galar": "Galarian Rapidash",
  "slowpoke-galar": "Galarian Slowpoke",
  "slowbro-galar": "Galarian Slowbro",
  "farfetchd-galar": "Galarian Farfetch'd",
  "weezing-galar": "Galarian Weezing",
  "mr-mime-galar": "Galarian Mr. Mime",
  "articuno-galar": "Galarian Articuno",
  "zapdos-galar": "Galarian Zapdos",
  "moltres-galar": "Galarian Moltres",
  "slowking-galar": "Galarian Slowking",
  "corsola-galar": "Galarian Corsola",
  "zigzagoon-galar": "Galarian Zigzagoon",
  "linoone-galar": "Galarian Linoone",
  "darumaka-galar": "Galarian Darumaka",
  "darmanitan-galar-standard": "Galarian Darmanitan",
  "darmanitan-galar-zen": "Galarian Darmanitan",
  "yamask-galar": "Galarian Yamask",
  "stunfisk-galar": "Galarian Stunfisk",
  "zygarde-10": "Zygarde",
  "cramorant-gulping": "Cramorant",
  "cramorant-gorging": "Cramorant",
  "toxtricity-low-key": "Toxtricity",
  "eiscue-noice": "Eiscue",
  "indeedee-female": "Indeedee",
  "morpeko-hangry": "Morpeko",
  "zacian-crowned": "Crowned Shield Zacian",
  "zamazenta-crowned": "Crowned Sword Zamazenta",
  "eternatus-eternamax": "Eternamax Eternatus",
  "urshifu-rapid-strike": "Rapid Strike Urshifu",
  "zarude-dada": "Zarude",
  "calyrex-ice": "Ice Rider Calyrex",
  "calyrex-shadow": "Shadow Rider Calyrex",
  "venusaur-gmax": "Gigantamax Venusaur",
  "charizard-gmax": "Gigantamax Charizard",
  "blastoise-gmax": "Gigantamax Blastoise",
  "butterfree-gmax": "Gigantamax Butterfree",
  "pikachu-gmax": "Gigantamax Pikachu",
  "meowth-gmax": "Gigantamax Meowth",
  "machamp-gmax": "Gigantamax Machamp",
  "gengar-gmax": "Gigantamax Gengar",
  "kingler-gmax": "Gigantamax Kingler",
  "lapras-gmax": "Gigantamax Lapras",
  "eevee-gmax": "Gigantamax Eevee",
  "snorlax-gmax": "Gigantamax Snorlax",
  "garbodor-gmax": "Gigantamax Garbodor",
  "melmetal-gmax": "Gigantamax Melmetal",
  "rillaboom-gmax": "Gigantamax Rillaboom",
  "cinderace-gmax": "Gigantamax Cinderace",
  "inteleon-gmax": "Gigantamax Inteleon",
  "corviknight-gmax": "Gigantamax Corviknight",
  "orbeetle-gmax": "Gigantamax Orbeetle",
  "drednaw-gmax": "Gigantamax Drednaw",
  "coalossal-gmax": "Gigantamax Coalossal",
  "flapple-gmax": "Gigantamax Flapple",
  "appletun-gmax": "Gigantamax Appletun",
  "sandaconda-gmax": "Gigantamax Sandaconda",
  "toxtricity-amped-gmax": "Gigantamax Toxtricity",
  "centiskorch-gmax": "Gigantamax Centiskorch",
  "hatterene-gmax": "Gigantamax Hatterene",
  "grimmsnarl-gmax": "Gigantamax Grimmsnarl",
  "alcremie-gmax": "Gigantamax Alcremie",
  "copperajah-gmax": "Gigantamax Copperajah",
  "duraludon-gmax": "Gigantamax Duraludon",
  "urshifu-single-strike-gmax": "Gigantamax Single Strike Urshifu",
  "urshifu-rapid-strike-gmax": "Gigantamax Rapid Strike Urshifu",
  "toxtricity-low-key-gmax": "Gigantamax Toxtricity",
  "growlithe-hisui": "Hisuian Growlithe",
  "arcanine-hisui": "Hisuian Arcanine",
  "voltorb-hisui": "Hisuian Voltorb",
  "electrode-hisui": "Hisuian Electrode",
  "typhlosion-hisui": "Hisuian Typhlosion",
  "qwilfish-hisui": "Hisuian Qwilfish",
  "sneasel-hisui": "Hisuian Sneasel",
  "samurott-hisui": "Hisuian Samurott",
  "lilligant-hisui": "Hisuian Lilligant",
  "zorua-hisui": "Hisuian Zorua",
  "zoroark-hisui": "Hisuian Zoroark",
  "braviary-hisui": "Hisuian Braviary",
  "sliggoo-hisui": "Hisuian Sliggoo",
  "goodra-hisui": "Hisuian Goodra",
  "avalugg-hisui": "Hisuian Avalugg",
  "decidueye-hisui": "Hisuian Decidueye",
  "dialga-origin": "Dialga",
  "palkia-origin": "Palkia",
  "basculin-white-striped": "Basculin",
  "basculegion-female": "Basculegion",
  "enamorus-therian": "Enamorus",
  "tauros-paldea-combat-breed": "Paldean Tauros",
  "tauros-paldea-blaze-breed": "Blaze Breed Paldean Tauros",
  "tauros-paldea-aqua-breed": "Aqua Breed Paldean Tauros",
  "wooper-paldea": "Paldean Wooper",
  "oinkologne-female": "Oinkologne",
  "dudunsparce-three-segment": "Dudunsparce",
  "palafin-hero": "Palafin",
  "maushold-family-of-three": "Maushold",
  "tatsugiri-droopy": "Tatsugiri",
  "tatsugiri-stretchy": "Tatsugiri",
  "squawkabilly-blue-plumage": "Squawkabilly",
  "squawkabilly-yellow-plumage": "Squawkabilly",
  "squawkabilly-white-plumage": "Squawkabilly",
  "gimmighoul-roaming": "Gimmighoul",
  "koraidon-limited-build": "Koraidon",
  "koraidon-sprinting-build": "Koraidon",
  "koraidon-swimming-build": "Koraidon",
  "koraidon-gliding-build": "Koraidon",
  "miraidon-low-power-mode": "Miraidon",
  "miraidon-drive-mode": "Miraidon",
  "miraidon-aquatic-mode": "Miraidon",
  "miraidon-glide-mode": "Miraidon",
  "ursaluna-bloodmoon": "Bloodmoon Ursaluna",
  "ogerpon-wellspring-mask": "Wellspring Mask Ogerpon",
  "ogerpon-hearthflame-mask": "Hearthflame Mask Ogerpon",
  "ogerpon-cornerstone-mask": "Cornerstone Mask Ogerpon",
}
